# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Weyland Joyner
tagline:             'Software Developer'
description:         For more info, check out my resume.
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# Custom vars
version:             1.0.0
markdown:            kramdown
plugins:             [jekyll-paginate]

kramdown:
  input: GFM
  syntax_highlighter: rouge
